/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package sr.thrift.smarthome;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-04-25")
public enum SwitchState implements org.apache.thrift.TEnum {
  ON(1),
  OFF(2);

  private final int value;

  private SwitchState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static SwitchState findByValue(int value) { 
    switch (value) {
      case 1:
        return ON;
      case 2:
        return OFF;
      default:
        return null;
    }
  }
}
